### ISSUE TITLE
Dependency on DBIish for NativeLibs

### ISSUE THREAD

**Issue by ugexe** [salortiz/JsonC#2]
It was a bit surprising to find DBIish installing when attempting to install a JSON parser

**Comment by ugexe** [comment]
I see you actually have a separate repo for NativeLibs, but it isn't showing up on the module list. I sent a PR to that repo that may fix that

**Comment by salortiz** [comment]
I have a problem: DBIish uses and provides a little NativeLibs.
As NativeLibs growing I create a separate repo for eventually publish it, but as DBIish is part of R\* I don't think that is a good idea add another external dependency to it.
So, meanwhile NativeLibs stabilizes and matures, JsonC is using the one provided by DBIish.

I'm thinking on a better solution.

**Comment by ugexe** [comment]
I see.

Ideally I think it could be renamed `DBIish::NativeLibs` and then in the `META6.json` it would have`"emulates" : { "DBIish::NativeLibs" : "NativeLibs:auth<github:salortiz>" }"` (see [S22#emulates](https://design.perl6.org/S22.html#emulates)). This would keep `DBIish::NativeLibs` in the `DBIish` namespace, but allow `use NativeLibs` to map to `use DBIish::NativeLibs`. However `emulates` functionality is NYI, so this is not a practical solution yet.

**Comment by salortiz** [comment]
All this happen because I discover that both zef and panda uses the union of all 'provides' to resolve dependencies (at first read of S22 I thought that only the main 'name'  was used).

In CURI can coexists different versions of the same module, and at `zef install …` and `use` time, the triad 'name/auth/ver' identify the requested distro/module, but I don't known yet if I can add `:ver(foo')` to `provides` keys of META6.json. That would allow us in our distributions, in theory, to `depends` on specific versions. So no need of different namespaces for the _same_ module. What do you think?

**Comment by ugexe** [comment]
I kinda wish `depends` did request only the distribution name and not the name of modules ("use" strings), but I don't know what other ramifications this could mean. S22 is ambiguous here, as the following would suggest `use` strings be used:
[To indicate alternatives, it is possible to specify a list of use strings](https://design.perl6.org/S22.html#depends)

Ideally all depends would/will declare specific versions (at least for production code). `zef` already supports depends in this format (`"depends" : [ "Foo::Bar:ver<1>:auth<foo:bar>" ]`), but I'm not sure if `panda` does. `zef` also supports versioning this way in the `provides`

**Comment by salortiz** [comment]
I just release NativeLibs v0.0.5 to the ecosystem.
Waiting for feedback.

**Comment by salortiz** [comment]
@ugexe: In my installation now I have both `NativeLibs:ver<0.0.2>` from a `zef install DBIish` and `NativeLibs:ver<0.0.5>` from a successful local `zef install .` from its source.

In the current `JsonC` code I'm using `use NativeLibs:ver<0.0.5>;` with success, a simple `use NativeLibs;` loads the former because, I guess, its first in CURI.
In JsonC's `META6.json` I'm using `…"depends" : [ "NativeLibs:ver<0.0.5+>" ],…`

So far all is working like charm. I think this can be closed now.

**Comment by salortiz** [comment]
The new v0.0.6, using standalone NativeLibs solved this. Closing.
